### PR TITLE
working on cmake for pynumero hsl

### PR DESCRIPTION
**Pull request by michaelbynum**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by Robbybp** [comment]
@michaelbynum were you able to run the tests when building with cmake? I got several errors upon loading the libraries due to undefined references to blas routines.

**Comment by Robbybp** [comment]
After specifying that the compiler should link a blas library via, e.g.
```cmake
TARGET_LINK_LIBRARIES( pynumero_MA27 ${HSL_LIBRARY} blas )
```
on line 151, I ran into an issue of the ctypes `LoadLibrary` method not being able to locate `libcoinhsl.so.0`, which I fixed by adding `$IPOPT_DIR/lib` to `LD_LIBRARY_PATH`. Is this something I should expect to need to do? It is not necessary when I compile by linking the solvers individually, at least via my makefiles. 

Regardless, after these changes I can build via cmake and run the tests successfully. If addition of `blas` should be added, what is the best way for me to incorporate this change in the PR? Seems silly for me to make a new branch to PR into yours, to PR into mine...

**Comment by michaelbynum** [comment]
@Robbybp I probably did not run into this because I already had my `LD_LIBRARY_PATH` pointing to `$IPOPT_DIR/lib` in my `.bash_profile`. Yes, I think this would be a requirement for linking against already built shared libraries for HSL. 

I can update the cmake files. I'll update the installation documentation.

**Comment by michaelbynum** [comment]
Actually it appears I did not run into this problem because I was on OSX. I just tested on linux and ran into the same problem. However, setting the `LD_LIBRARY_PATH` fixed the problem without modifying `CMakeLists.txt` to specify linking against blas. Thoughts?

**Comment by Robbybp** [comment]
Which problem did you encounter? The undefined blas routines, or the unable to find coinhsl? 

I just re-built and tested with an updated `LD_LIBRARY_PATH` but no explicit blas dependency, and it seemed to work, so I'll go ahead and merge your branch. 

Also, the reason I didn't need to update `LD_LIBRARY_PATH` when linking individually was that I did `make install` for ma57 and then forgot about it. D'oh

**Comment by michaelbynum** [comment]
The unable to find coinhsl problem.

**Pull request merged**
